import { buildProductArtwork } from "./helpers.js";

const baseProducts = [
  {
    id: "TSHIRT_001",
    name: "Performance Training Tee",
    price: 999,
    category: "T-Shirts",
    material: "Moisture-wicking Polyester",
    material_tag: "Moisture-wicking",
    colors: ["Electric Blue", "Black", "Slate Grey"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    activity: "Gym",
    fit: "Regular",
    description:
      "Fast-dry training tee built for high-intensity sessions with breathable stretch and sweat control.",
    material_composition: "88% Polyester, 12% Elastane",
    accent: "#2563eb",
    background: "#dbeafe",
    secondary: "#f97316",
  },
  {
    id: "TSHIRT_002",
    name: "Aero Run Lite Tee",
    price: 1099,
    category: "T-Shirts",
    material: "Featherweight Polyester Mesh",
    material_tag: "Polyester",
    colors: ["Neon Lime", "Graphite", "White"],
    sizes: ["S", "M", "L", "XL"],
    activity: "Running",
    fit: "Lightweight",
    description:
      "Ultra-light run tee with zoned ventilation and reflective detailing for tempo days and long miles.",
    material_composition: "92% Recycled Polyester, 8% Spandex",
    accent: "#16a34a",
    background: "#dcfce7",
    secondary: "#0f172a",
  },
  {
    id: "TSHIRT_003",
    name: "Flow Motion Tee",
    price: 1199,
    category: "T-Shirts",
    material: "Soft Cotton Blend",
    material_tag: "Blend",
    colors: ["Sand", "Olive", "Dusty Rose"],
    sizes: ["XS", "S", "M", "L", "XL"],
    activity: "Yoga",
    fit: "Baggy",
    description:
      "Relaxed studio tee with a draped shoulder line and soft-touch finish for low-impact movement.",
    material_composition: "55% Cotton, 40% Modal, 5% Elastane",
    accent: "#ea580c",
    background: "#ffedd5",
    secondary: "#22c55e",
  },
  {
    id: "TSHIRT_004",
    name: "Everyday Club Tee",
    price: 899,
    category: "T-Shirts",
    material: "Premium Cotton",
    material_tag: "Cotton",
    colors: ["White", "Ink Navy", "Clay"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    activity: "Casual",
    fit: "Regular",
    description:
      "Structured everyday tee with a polished neckline, clean drape, and comfort that carries beyond the gym.",
    material_composition: "100% Cotton",
    accent: "#0f172a",
    background: "#e2e8f0",
    secondary: "#fb7185",
  },
  {
    id: "TSHIRT_005",
    name: "Court Drive Tee",
    price: 1299,
    category: "T-Shirts",
    material: "Performance Blend",
    material_tag: "Blend",
    colors: ["Crimson", "Black", "Bone"],
    sizes: ["S", "M", "L", "XL"],
    activity: "Sports",
    fit: "Regular",
    description:
      "Built for all-round play with anti-odor comfort, shoulder mobility, and a clean sport silhouette.",
    material_composition: "70% Polyester, 25% Cotton, 5% Elastane",
    accent: "#dc2626",
    background: "#fee2e2",
    secondary: "#1d4ed8",
  },
  {
    id: "TSHIRT_006",
    name: "Velocity Muscle Tee",
    price: 949,
    category: "T-Shirts",
    material: "Sweatwise Jersey",
    material_tag: "Moisture-wicking",
    colors: ["Storm", "Blue Flame", "Cobalt"],
    sizes: ["M", "L", "XL", "XXL"],
    activity: "Gym",
    fit: "Lightweight",
    description:
      "Sleeveless-inspired cut in a tee format, designed for lifting sessions and warm studio environments.",
    material_composition: "90% Polyester, 10% Elastane",
    accent: "#0284c7",
    background: "#e0f2fe",
    secondary: "#f97316",
  },
  {
    id: "TSHIRT_007",
    name: "Pace Relay Tee",
    price: 999,
    category: "T-Shirts",
    material: "Breathable Poly Blend",
    material_tag: "Moisture-wicking",
    colors: ["Coral", "Midnight", "Mist"],
    sizes: ["XS", "S", "M", "L"],
    activity: "Running",
    fit: "Regular",
    description:
      "Balanced run tee with soft hand-feel, sweat dispersal, and a fit that stays easy through recovery miles.",
    material_composition: "82% Polyester, 18% Elastane",
    accent: "#fb7185",
    background: "#ffe4e6",
    secondary: "#1d4ed8",
  },
  {
    id: "TSHIRT_008",
    name: "Studio Ease Tee",
    price: 1049,
    category: "T-Shirts",
    material: "Cloud Cotton",
    material_tag: "Cotton",
    colors: ["Lilac", "Off White", "Forest"],
    sizes: ["XS", "S", "M", "L", "XL"],
    activity: "Yoga",
    fit: "Baggy",
    description:
      "Easy oversized tee with a fluid hem, soft cotton body, and calm neutral palette for studio days.",
    material_composition: "95% Cotton, 5% Elastane",
    accent: "#7c3aed",
    background: "#ede9fe",
    secondary: "#14b8a6",
  },
];

export const PRODUCTS = baseProducts.map((product) => ({
  ...product,
  image_url: buildProductArtwork({
    name: product.name,
    accent: product.accent,
    background: product.background,
    secondary: product.secondary,
    badge: product.activity,
  }),
  reason: `Popular with ${product.activity.toLowerCase()} members`,
}));

export const MEMBERS = [
  {
    phone: "9876543210",
    name: "Raj Kumar",
    activity: "Gym",
    fitness_level: "Intermediate",
    preferred_fit: "Regular",
    material_preference: "Moisture-wicking",
  },
  {
    phone: "9123456780",
    name: "Neha Sharma",
    activity: "Running",
    fitness_level: "Advanced",
    preferred_fit: "Lightweight",
    material_preference: "Polyester",
  },
  {
    phone: "9988776655",
    name: "Aman Verma",
    activity: "Yoga",
    fitness_level: "Beginner",
    preferred_fit: "Baggy",
    material_preference: "Blend",
  },
];

export const STORES = [
  { store_id: "STORE_001", store_name: "EBO - MG Road", distance_km: 0, is_primary: true },
  { store_id: "STORE_002", store_name: "EBO - Indiranagar", distance_km: 4.2, is_primary: false },
  { store_id: "STORE_003", store_name: "EBO - Koramangala", distance_km: 6.8, is_primary: false },
  { store_id: "STORE_004", store_name: "EBO - Orion Mall", distance_km: 9.4, is_primary: false },
];

export const INVENTORY_ENTRIES = [
  { product_id: "TSHIRT_001", store_id: "STORE_001", size: "M", color: "Electric Blue", quantity: 5 },
  { product_id: "TSHIRT_001", store_id: "STORE_001", size: "L", color: "Black", quantity: 4 },
  { product_id: "TSHIRT_001", store_id: "STORE_002", size: "M", color: "Slate Grey", quantity: 3 },
  { product_id: "TSHIRT_001", store_id: "STORE_003", size: "S", color: "Black", quantity: 6 },
  { product_id: "TSHIRT_002", store_id: "STORE_001", size: "M", color: "Neon Lime", quantity: 2 },
  { product_id: "TSHIRT_002", store_id: "STORE_002", size: "L", color: "Graphite", quantity: 4 },
  { product_id: "TSHIRT_002", store_id: "STORE_004", size: "S", color: "White", quantity: 5 },
  { product_id: "TSHIRT_003", store_id: "STORE_001", size: "S", color: "Sand", quantity: 1 },
  { product_id: "TSHIRT_003", store_id: "STORE_003", size: "M", color: "Olive", quantity: 3 },
  { product_id: "TSHIRT_003", store_id: "STORE_004", size: "L", color: "Dusty Rose", quantity: 2 },
  { product_id: "TSHIRT_004", store_id: "STORE_001", size: "M", color: "White", quantity: 7 },
  { product_id: "TSHIRT_004", store_id: "STORE_001", size: "L", color: "Ink Navy", quantity: 4 },
  { product_id: "TSHIRT_004", store_id: "STORE_002", size: "XL", color: "Clay", quantity: 5 },
  { product_id: "TSHIRT_005", store_id: "STORE_001", size: "M", color: "Crimson", quantity: 3 },
  { product_id: "TSHIRT_005", store_id: "STORE_002", size: "L", color: "Black", quantity: 2 },
  { product_id: "TSHIRT_005", store_id: "STORE_003", size: "S", color: "Bone", quantity: 4 },
  { product_id: "TSHIRT_006", store_id: "STORE_001", size: "L", color: "Blue Flame", quantity: 6 },
  { product_id: "TSHIRT_006", store_id: "STORE_004", size: "XL", color: "Storm", quantity: 5 },
  { product_id: "TSHIRT_007", store_id: "STORE_001", size: "M", color: "Coral", quantity: 4 },
  { product_id: "TSHIRT_007", store_id: "STORE_002", size: "S", color: "Mist", quantity: 2 },
  { product_id: "TSHIRT_007", store_id: "STORE_003", size: "L", color: "Midnight", quantity: 3 },
  { product_id: "TSHIRT_008", store_id: "STORE_001", size: "S", color: "Lilac", quantity: 2 },
  { product_id: "TSHIRT_008", store_id: "STORE_003", size: "M", color: "Off White", quantity: 3 },
  { product_id: "TSHIRT_008", store_id: "STORE_004", size: "L", color: "Forest", quantity: 2 },
];
